# Docker Compose for RTSP Camera ROS 1 Noetic on Jetson Orin NX
# Optimized for Jetson hardware with L4T base image

version: '3.8'

services:
  rtsp-cam:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: rtsp_cam:jetson-noetic
    container_name: rtsp_cam_jetson
    restart: unless-stopped
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
      - DECODER_TYPE=jetson
      - CUDA_VISIBLE_DEVICES=0
      - GST_PLUGIN_PATH=/usr/lib/aarch64-linux-gnu/gstreamer-1.0
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH
    volumes:
      - ../config/rtsp_cam_config.yaml:/catkin_ws/src/rtsp_cam/config/rtsp_cam_config.yaml:ro
      - ${PHOTO_DIR:-/tmp/rtsp_cam_photos}:/tmp/rtsp_cam_photos
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra:ro
      - /usr/lib/aarch64-linux-gnu/gstreamer-1.0:/usr/lib/aarch64-linux-gnu/gstreamer-1.0:ro
    devices:
      - /dev/nvhost-ctrl
      - /dev/nvhost-ctrl-gpu
      - /dev/nvhost-prof-gpu
      - /dev/nvmap
      - /dev/nvhost-gpu
      - /dev/nvhost-as-gpu
      - /dev/nvhost-ctrl-isp
      - /dev/nvhost-ctrl-vi
    ipc: host
    privileged: true
    command: ["roslaunch", "rtsp_cam", "rtsp_cam.launch"]
