# Docker Compose for RTSP Camera ROS 1 Noetic on Jetson Orin NX
# Optimized for Jetson hardware with L4T base image

version: '3.8'

services:
  rtsp-cam:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: rtsp_cam:jetson-noetic
    container_name: rtsp_cam_jetson
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
      - DECODER_TYPE=jetson
      - CUDA_VISIBLE_DEVICES=0
      - GST_PLUGIN_PATH=/host/gstreamer-1.0:/usr/lib/aarch64-linux-gnu/gstreamer-1.0:/usr/lib/aarch64-linux-gnu/tegra-mmapi
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra-mmapi:/opt/nvidia/vpi2/lib64:/usr/lib/aarch64-linux-gnu:/usr/local/lib
      - NVMEDIA_ENABLE_TRACKING=1
      - NVMEDIA_ENABLE_PROFILING=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ../config/rtsp_cam_config.yaml:/catkin_ws/src/rtsp_cam/config/rtsp_cam_config.yaml:ro
      - ${PHOTO_DIR:-/tmp/rtsp_cam_photos}:/tmp/rtsp_cam_photos
      # Mount host Jetson plugins to avoid GLIBC conflicts
      - /usr/lib/aarch64-linux-gnu/gstreamer-1.0:/host/gstreamer-1.0:ro
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra:ro
    devices:
      - /dev/nvhost-ctrl
      - /dev/nvhost-ctrl-gpu
      - /dev/nvhost-prof-gpu
      - /dev/nvmap
      - /dev/nvhost-gpu
      - /dev/nvhost-as-gpu
      - /dev/nvhost-ctrl-isp
      - /dev/nvhost-ctrl-vi
      - /dev/tegra_dc_ctrl
      - /dev/tegra_dc_0
      - /dev/tegra_dc_1
    ipc: host
    privileged: true
    command: ["roslaunch", "rtsp_cam", "rtsp_cam.launch"]
