# RTSP Camera Configuration for ROS 1 Noetic
# This file contains all the configuration parameters for generic RTSP cameras

# Camera connection parameters
camera_ip: "192.168.51.106"
camera_port: 554
username: "admin"
password: "verlab10"

# RTSP stream URLs (customize for your camera)
main_stream_url: "rtsp://admin:verlab10@192.168.51.106/cam/realmonitor?channel=1&subtype=0"
sub_stream_url: "rtsp://admin:verlab10@192.168.51.106/cam/realmonitor?channel=1&subtype=1"

# PTZ control parameters (optional, for PTZ cameras)
onvif_port: 8999
http_port: 80
use_onvif: false  # Use HTTP interface when available
ptz_enabled: true

# Stream configuration
main_stream_enabled: true
sub_stream_enabled: true
encoding: "h264"  # Options: "h264", "h265"
frame_rate: 30
# Main stream resolution (4M camera stream ≈ 2560x1440)
main_resolution_width: 2560
main_resolution_height: 1440
# Secondary stream resolution (VGA)
sub_resolution_width: 640
sub_resolution_height: 480
# Default/backward compatibility
resolution_width: 2560
resolution_height: 1440

# Hardware decoding options: "software", "nvidia", "jetson", "vaapi"
decoder_type: "jetson"  # Optimized for Jetson Orin NX

# GStreamer pipeline configuration (auto-generated based on decoder_type)
gst_pipeline_main: ""
gst_pipeline_sub: ""

# PTZ movement parameters
pan_speed: 0.5
tilt_speed: 0.5
zoom_speed: 0.5
auto_stop_timeout: 2.0  # Auto-stop timeout in seconds

# Photo capture parameters
photo_save_path: "/tmp/rtsp_cam_photos"
photo_format: "jpg"
photo_quality: 95

# ROS topics and services
main_image_topic: "camera/main/image_raw"
sub_image_topic: "camera/sub/image_raw"
camera_info_topic: "camera/camera_info"
ptz_status_topic: "camera/ptz_status"
photo_service_name: "camera/take_photo"

# Camera info parameters
camera_name: "rtsp_camera"
camera_frame_id: "camera_link"

# Performance parameters
buffer_size: 1
queue_size: 10
timeout_ms: 5000 